### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by anotherras** [Ramprasad-Group/polymer_information_extraction#2]
Hello.
First of all, thank you for sharing your great work. I was impressed by your work and tried to reproduce your work to get insights.When I ran data_extraction.py, I found that normalization files and property_metadata_file were missing. Could you please provide these files?

**Comment by pranav-s** [comment]
Hello,
You can find these files [here](https://github.com/Ramprasad-Group/PolymerSolarCellsML/tree/main/metadata).
